name: Deploy to staging
on:
  issue_comment:
    types: [created]
jobs:
  staging:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJSON('["ajor", "danobi", "fbs", "jordalgo", "tyroguru", "viktormalik"]'), github.actor) && github.event.issue.pull_request && github.event.comment.body == '/stage' }}
    steps:
      - name: Get Pull Request Hash
        id: sha
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo, number} = context.issue
            const pr = await github.pulls.get({
              owner,
              repo,
              pull_number: number,
            });
            return pr.data.head.sha
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.sha.outputs.result }}
          fetch-depth: 0
      - name: Rebase website-staging
        run: |
          git config --global user.name 'Staging Sync'
          git config --global user.email ''
          git checkout -b current
          git clone https://bpftrace:${{ secrets.SYNC_WEBSITE_STAGING }}@github.com/bpftrace/website-staging.git
          cd website-staging
          git remote add pr ../
          git fetch pr
          git reset --hard pr/current
          git cherry-pick origin/staging-config
          git push -f
      - name: Message success
        if: ${{ success() }}
        uses: actions/github-script@v7
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deploying pull request to https://staging.bpftrace.org/',
            });
