name: Sync pre-release docs from main repo

on:
  schedule:
   # run daily at 8am
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.ADOC_SYNC }}

      - name: Push
        run: |
          npm install
          git config --local user.email "bpftrace@gmail.com"
          git config --local user.name "GitHub Actions"
          git clone https://github.com/bpftrace/bpftrace.git
          npm run make-docs
          git add src/pages/docs/pre-release/
          git commit -m 'Sync Pre-release docs from main repo' || true
          git push
