name: Sync CSS with docs-website

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs-website
        uses: actions/checkout@v4

      - name: Push
        run: |
          git config --global user.name 'Style Sync'
          git config --global user.email ''
          git clone https://bpftrace:${{ secrets.SYNC_DOCS_WEBSITE }}@github.com/bpftrace/docs-website.git
          cd docs-website
          cp ../src/css/custom.css src/css/custom.css
          git add src/css/custom.css
          git commit -m 'Sync CSS from website' || true
          git push
