name: Sync pre-release docs from main repo

on:
  schedule:
   # run daily at 8am
    - cron:  '0 8 * * *'
  workflow_dispatch:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.x]
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.ADOC_SYNC }}

      - name: Push
        run: |
          npm install
          git config --global user.name 'pre-release-docs-sync'
          git config --global user.email ''
          git clone https://bpftrace:${{ secrets.SYNC_DOCS_WEBSITE }}@github.com/bpftrace/bpftrace.git
          npm run make-pre-release-docs
          git add src/pages/docs/pre-release.js
          git commit -m 'Sync Pre-release docs from main repo' || true
          git push
